//AUTH
export const LOGIN = 'LOGIN';
export const UNAUTHORISED = 'UNAUTHORISED';
export const AUTHENTICATING = 'AUTHENTICATING';
// export const AUTHENTICATING_STAFF = 'AUTHENTICATING_STAFF';
// export const AUTHENTICATED_STAFF = 'AUTHENTICATED_STAFF';
// export const UNAUTHORISED_STAFF = 'UNAUTHORISED_STAFF';
// export const LOGIN_STAFF_ERROR = 'LOGIN_STAFF_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const PRE_LOGOUT = 'PRE_LOGOUT';

//FACIAS
export const SELECT_FACIA = 'SELECT_FACIA';
export const FETCH_FACIAS = 'FETCH_FACIAS';
export const LOADING_FACIAS = 'LOADING_FACIAS';
export const FACIAS_ERROR = 'FACIAS_ERROR';
export const LOADING_FACIA = 'LOADING_FACIA';
export const FACIA_ERROR = 'FACIA_ERROR';
export const CLEAR_FACIA = 'CLEAR_FACIA';
export const FETCH_FACIA = 'FETCH_FACIA';

//CATEGORY
export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const FETCH_MORE_PRODUCTS = 'FETCH_MORE_PRODUCTS';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_CATEGORY_SORT = 'SET_CATEGORY_SORT';

//SEARCH
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_IMAGE_SEARCH_VALUE = 'SET_IMAGE_SEARCH_VALUE';
export const LOADING_SEARCH = 'LOADING_SEARCH';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const DO_SEARCH = 'DO_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SEARCH_MORE_PRODUCTS = 'SEARCH_MORE_PRODUCTS';
export const SET_SEARCH_FACIA = 'SET_SEARCH_FACIA';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_SEARCH_FACIAS = 'SET_SEARCH_FACIAS';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';
export const SET_SEARCH_SORT = 'SET_SEARCH_SORT';

//PRODUCT
export const LOADING_PRODUCT = 'LOADING_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';

//USER
export const FETCH_USER = 'FETCH_USER';
export const CREATING_USER_ADDRESS = 'CREATING_USER_ADDRESS';
export const USER_ERROR = 'USER_ERROR';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const CLEAR_ADDRESS = 'CLEAR_ADDRESS';
export const FETCHING_USER = 'FETCHING_USER';

//BASKET
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const UPDATE_BASKET_ITEMS = 'UPDATE_BASKET_ITEMS';
export const ADDING_TO_BASKET = 'ADDING_TO_BASKET';
export const UPDATE_BASKET = 'UPDATE_BASKET';
export const BASKET_ERROR = 'BASKET_ERROR';
export const REMOVING_FROM_BASKET = 'REMOVING_FROM_BASKET';
export const UPDATING_BASKET = 'UPDATING_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const CLEAR_BASKET_STATUS = 'CLEAR_BASKET_STATUS';

//BUYNOWBASKET
export const ADDING_TO_BUY_NOW_BASKET = 'ADDING_TO_BUY_NOW_BASKET';
export const UPDATING_BUY_NOW_BASKET = 'UPDATING_BUY_NOW_BASKET';
export const FETCH_BUY_NOW_BASKET = 'FETCH_BUY_NOW_BASKET';
export const UPDATE_BUY_NOW_BASKET = 'UPDATE_BUY_NOW_BASKET';
export const CLEAR_BUY_NOW_BASKET = 'CLEAR_BUY_NOW_BASKET';
export const BUY_NOW_BASKET_ERROR = 'BUY_NOW_BASKET_ERROR';

//DELIVERYMETHODS
export const FETCHING_DELIVERY_METHODS = 'FETCHING_DELIVERY_METHODS';
export const DELIVERY_METHODS = 'DELIVERY_METHODS';
export const DELIVERY_METHODS_ERROR = 'DELIVERY_METHODS_ERROR';

//UI
export const DISMISS_WELCOME_MESSAGE = 'DISMISS_WELCOME_MESSAGE';
export const DISMISS_DISPATCH_TOAST = 'DISMISS_DISPATCH_TOAST';
export const SET_USE_FINGERPRINT = 'SET_USE_FINGERPRINT';

//ORDERS
export const ORDER_CREATED = 'ORDER_CREATED';
export const FETCH_ORDER = 'FETCH_ORDER';
export const LOADING_ORDERS = 'LOADING_ORDERS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SELECT_ORDER = 'SELECT_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';

//WISHLIST
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';

//RECENTLY VIEWED
export const ADD_TO_RECENTLY_VIEWED = 'ADD_TO_RECENTLY_VIEWED';
export const REMOVE_FROM_RECENTLY_VIEWED = 'REMOVE_FROM_RECENTLY_VIEWED';
export const UPDATE_RECENTLY_VIEWED_ITEM = 'UPDATE_RECENTLY_VIEWED_ITEM';

//HOME
export const FETCH_HOME = 'FETCH_HOME';
export const LOADING_HOME = 'LOADING_HOME';
export const HOME_ERROR = 'HOME_ERROR';

//PAGE
export const FETCH_PAGE = 'FETCH_PAGE';
export const LOADING_PAGE = 'LOADING_PAGE';
export const PAGE_ERROR = 'PAGE_ERROR';
